model: PointNet
mission: classification  # classification / part segmentation / scene segmentation
mode: train  # train or test
device: cuda  # cuda or cpu
pointNum: 1000  # cls: 1000 / part_seg: 2048 / scene segmentation: 4096
datasetRootDir: ./Dataset
numClass: 2
batchSize: 2
k: 5  # the parameter of DGCNN and GANN
kmax: 20  # the parameter of GANN

# train
# s3dis: [0, 12] shapenet: [0, 5] modelnet40: [0, 39]
optimizer: Adam  # Adam, SGD, RMSprop, Nadam
learningRate: 0.0001
epochs: 10
val: 1  # 1->yes 0->no
summaryLogDir: "./summary"
modelSaveDir: "./weights"
tmpSaveDir: "./tmp"
loadModelDir: "0"

# test
weight: "pointnet_last.pt"
