model: DGCNN
mission: classification  # classification / part segmentation / scene segmentation
mode: train  # train or test
device: cuda  # cuda or cpu
pointNum: 1024  # cls: 1000 / part_seg: 2048 / scene segmentation: 4096
numClass: 40
batchSize: 2
k: 40  # the parameter of DGCNN and GANN
kmax: 20  # the parameter of GANN

# train
# s3dis: [0, 12] shapenet: [0, 5] modelnet40: [0, 39]
optimizer: Adam  # Adam, SGD, RMSprop, Nadam
learningRate: 0.0001
epochs: 100
val: 0  # 1->yes 0->no
summaryLogDir: "./summary"
modelSaveDir: "./weights"
tmpSaveDir: "./tmp"
loadModelDir: "0"

# test
weight: "pointnet_last.pt"
